sudo: required
services:
  - docker

before_install:
  - docker build -t bluesaluman/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run bluesaluman/react-test npm test -- --coverage

after_success: 
  - docker build -t bluesaluman/multi-client ./client
  - docker build -t bluesaluman/multi-nginx ./nginx
  - docker build -t bluesaluman/multi-server ./server
  - docker build -t bluesaluman/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push bluesaluman/multi-client
  - docker push bluesaluman/multi-nginx
  - docker push bluesaluman/multi-server
  - docker push bluesaluman/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1